Prepare sdk 3.1.0 and CLI 1.8.1 release
celo-org/celo-monorepo pull request #10093
Opened 2023-01-04 23:43 UTC by aaronmgdr

### Description

bumps versions

2023-01-05 15:22 UTC, lvpeschke approved these changes
LGTM

2023-01-05 15:48 UTC, soloseng approved these changes
🚀

2023-01-05 22:32 UTC, aaronmgdr commented
plan to merge this next week after taking the releases out of beta

2023-01-10 16:18 UTC, alecps requested changes

2023-01-10 16:18 UTC, alecps commented on packages/phone-number-privacy/combiner/package.json
> +    "@celo/identity": "^3.1.0",
I'd like to better understand why this is necessary before making this change

2023-01-10 19:53 UTC, alecps approved these changes
spoke with Aaron and these version changes make sense to me 👍

2023-01-10 22:43 UTC, merged