Delegation CLI commands
celo-org/celo-monorepo pull request #10642
Opened 2023-10-04 09:58 UTC by pahor167

### Description

PR introduces new cli commands related to delegation
delegate
revoke-delegate
max-delegatees-count
update-delegated-amount

2023-10-04 10:05 UTC, aaronmgdr commented on packages/cli/src/commands/lockedgold/update-delegated-amount.ts
> +    await newCheckBuilder(this).isAccount(address).isAccount(to).isAccount(to).runChecks()
isAccount(to) is called twice

2023-10-07 19:27 UTC, therealharpaljadeja commented
Can we add the following commands too? @pahor167 

- total percent delegated by an account
- list of delegatees for a delegator
- total delegated votes to an address

<img width="1026" alt="image" src="https://github.com/celo-org/celo-monorepo/assets/38040789/9128ef75-32ff-4095-86ef-b30bb5f06883">

2023-10-11 10:33 UTC, pahor167 commented
> Can we add the following commands too? @pahor167
> 
> * total percent delegated by an account
> * list of delegatees for a delegator
> * total delegated votes to an address
> 
> <img alt="image" width="1026" src="https://user-images.githubusercontent.com/38040789/273405473-9128ef75-32ff-4095-86ef-b30bb5f06883.png">

I added new command delegate-info that shows required information

2023-10-19 18:33 UTC, therealharpaljadeja approved these changes
LGTM!

2023-10-20 08:08 UTC, aaronmgdr requested changes
For PRs that modify published packages such as CLI  Please add a changeset by running `yarn changeset add`

2023-10-20 08:13 UTC, aaronmgdr commented
Why is this not merging into master?

2023-10-25 09:36 UTC, pahor167 commented
> For PRs that modify published packages such as CLI Please add a changeset by running `yarn changeset add`

There doesn't seem to be any changeset in CR10 yet (we will have to wait for it to be merged to master probably)

2023-10-25 09:36 UTC, pahor167 commented
> Isn't CR10 already out? Why is this not merging into master?

Unfortunately CR10 was not merged into master yet @martinvol is working on that

2023-11-06 11:53 UTC, therealharpaljadeja commented
@pahor167 CR10 is merged!

2023-11-06 13:32 UTC, pahor167 commented
I had some issues rebasing to master so I published new PR https://github.com/celo-org/celo-monorepo/pull/10702

2023-11-06 13:32 UTC, closed without merging