WIP blockchain parameters
celo-org/celo-monorepo pull request #10673
Opened 2023-10-20 16:32 UTC by martinvol

### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### Documentation

_The set of community facing docs that have been added/modified because of this change_

2024-01-03 17:21 UTC, soloseng reviewed
Reviewed. Left a few comments.

Test looks good, but I noticed that the test for this contract are not actually running(local and CI). So it's difficult to tell if they are passing.

2024-01-03 17:21 UTC, soloseng commented on packages/protocol/test-sol/governance/network/BlockchainParameters.t.Sol
> +  uint256 constant EPOCH_SIZE = 100;
this is set twice. once in constants, once here

2024-01-03 17:21 UTC, soloseng commented on packages/protocol/test-sol/identity/Random.t.sol
> +    // TODO add travel here
Is this TODO still pending?

2024-01-03 17:21 UTC, soloseng commented on packages/protocol/test-sol/governance/network/BlockchainParameters.t.Sol
> +  function test_setBlockGasLimit_set_variable() public {
Duplicate test

2024-01-03 17:21 UTC, soloseng commented on packages/protocol/test-sol/governance/network/BlockchainParameters.t.Sol
> +  function test_ShouldRevert_WhenCalledByNonOwner() public {
```suggestion
  function test_RevertWhen_CalledByNonOwner() public {
```

2024-01-03 17:21 UTC, soloseng commented on packages/protocol/test-sol/governance/network/BlockchainParameters.t.Sol
> +    vm.prank(msg.sender);
NIT: to keep with the format we have been using, it might be a ggod Idea to create a `nonOwner` account to submit these transactions

2024-01-03 17:21 UTC, soloseng commented on packages/protocol/test-sol/governance/network/BlockchainParameters.t.Sol
> +  function test_ShoudEmitBlockGasLimitSet () public {
rename test based on the expected event name

2024-01-03 17:21 UTC, soloseng commented on packages/protocol/test-sol/governance/network/BlockchainParameters.t.Sol
> +  function test_ShouldRevert_WhenCalledByNonOwner() public {
```suggestion
  function test_RevertWhen_CalledByNonOwner() public {
```

2024-01-03 17:21 UTC, soloseng commented on packages/protocol/test-sol/governance/network/BlockchainParameters.t.Sol
> +  function test_ShouldRevert_WhenNotSet() public {
NIT: rename test in an effort to stick to the recommended [best practices](https://book.getfoundry.sh/tutorials/best-practices#general-contract-guidance). Here and throughout

2024-01-03 17:21 UTC, soloseng commented on packages/protocol/test-sol/governance/network/BlockchainParameters.t.Sol
> +  function test_ShoudEmitUptimeLookbackWindowSet () public {
```suggestion
  function test_Emit_UptimeLookbackWindowSet () public {
```

2024-01-03 17:21 UTC, soloseng commented on packages/protocol/test-sol/governance/network/BlockchainParameters.t.Sol
> +  function test_ShoudEmitIntrinsicGasForAlternativeFeeCurrencySet() public {
```suggestion
  function test_Emit_IntrinsicGasForAlternativeFeeCurrencySet() public {
```

2024-01-03 17:21 UTC, soloseng commented on packages/protocol/test-sol/governance/network/BlockchainParameters.t.Sol
> +  function test_ShoudEmitIntrinsicGasForAlternativeFeeCurrencySet() public {
Might be worth splitting this tet into multiple test, since there are multiple events being emited and the test name is not descriptive of that.

2024-01-03 17:21 UTC, soloseng commented on packages/protocol/test-sol/governance/network/BlockchainParameters.t.Sol
> +contract BlockchainParametersTest_initialize is BlockchainParametersTest {
So far, the conventions has been to use cammel case for the test contract name.


```suggestion
contract BlockchainParametersTestInitialize is BlockchainParametersTest {
```

2024-01-04 12:58 UTC, martinvol commented on packages/protocol/test-sol/governance/network/BlockchainParameters.t.Sol
> +  uint256 constant EPOCH_SIZE = 100;
If I use the epoch size in constants there's one edge case it wont be able to test.

2024-01-04 17:17 UTC, soloseng requested changes
the test is not actually running

2024-01-05 15:20 UTC, soloseng approved these changes

2024-01-08 17:34 UTC, merged