Fix/abis handle contracts 08
celo-org/celo-monorepo pull request #10734
Opened 2023-11-13 18:41 UTC by nicolasbrugneaux

TODO description

2023-11-14 08:24 UTC, aaronmgdr commented on packages/protocol/abis/tsconfig.json
> +    "jsx": "preserve",
this isn't needed. as this is not a react app

2023-11-14 08:27 UTC, aaronmgdr commented on packages/protocol/scripts/prepare-contracts-and-abis-publishing.ts
> +// Merge contracts-0.8, contracts-mento, etc.. at the root of the build dir
very grateful for these comments

2023-11-14 13:47 UTC, aaronmgdr commented on packages/protocol/abis/package.json
> +  "module": "./lib/esm/index.js",
why is types not needed anymore?

2023-11-14 14:25 UTC, nicolasbrugneaux commented on packages/protocol/abis/package.json
> +  "module": "./lib/esm/index.js",
oh shoot

2023-11-16 12:54 UTC, aaronmgdr approved these changes

2023-11-16 12:54 UTC, aaronmgdr requested changes
soorry

2023-11-16 12:54 UTC, aaronmgdr commented
sorry i want to release packages before making big update to master

2023-11-16 13:08 UTC, aaronmgdr approved these changes
ok go

2023-11-16 13:08 UTC, merged