fix: celocli network:contracts command post Mento upgrade 04
celo-org/celo-monorepo pull request #10792
Opened 2023-11-28 13:19 UTC by philbow61

### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### Documentation

_The set of community facing docs that have been added/modified because of this change_

2023-11-28 13:23 UTC, aaronmgdr requested changes
Going to be strict and ask for a pr description and  patch changeset (from root run yarn changeset add)

2023-11-28 13:49 UTC, philbow61 commented
@aaronmgdr updated 🙏

2023-11-28 14:00 UTC, aaronmgdr commented
the description makes me think its better to wait to merge this pr. or that something else needs to be done. 

am i misreading? 

if this was merged and the cli was released would cli break on mainnet?

2023-11-29 10:28 UTC, philbow61 commented
@aaronmgdr From our perspective, the PR can be merged now so that the command won't break in the future when we do the next mento upgrade (MU04) on Alfajores and mainnet. The only side effect would be that until we do the upgrade there won't be a version in the output for the StableToken contracts, which shouldn't be a big deal.

Regarding the FeeHandler: this is currently breaking the network:contracts command on Baklava but it was not caused by us, Looks like someone else pointed it to the wrong address while deploying on testnets (currently 0x...01). It either needs to be pointed to address(0) or to the correct contract address (is it even deployed on Baklava?) Nonetheless this is not related to our PR, just something that we noticed while working on it

2023-11-29 11:53 UTC, aaronmgdr approved these changes

2023-11-29 12:17 UTC, 0xarthurxyz commented
On celocli v3.1.0, it actually looks like multiple proxy/implementation addresses are incorrect:

```sh
$ celocli --version             
@celo/celocli/3.1.0 darwin-arm64 node-v18.16.1
~  $ celocli network:contracts
 Contract                Proxy                                      Implementation                             Version CELO      cUSD      cEUR      cREAL     
 ─────────────────────── ────────────────────────────────────────── ────────────────────────────────────────── ─────── ───────── ───────── ───────── ───────── 
 Accounts                0xed7f51A34B4e71fbE69B3091FcF879cD14bD73A9 0x133D9408098b72a18B6c79f06BC62965D1B59cC1 1.1.4.1 2.000e+19 2.000e+19 1.000e+19 0         
 Attestations            0xAD5E5722427d79DFf28a4Ab30249729d1F8B4cc0 0xA758e8f4f79AB72184914343CaAb2E2162fdDd3D 1.2.0.0 0         2.134e+21 0         0         
 BlockchainParameters    0xE5aCbb07b4Eed078e39D50F66bF0c80cF1b93abe 0x029d8a20D86157F47CcbEE5209DEe0591dD2eB70 1.3.0.0 0         0         0         0         
 DoubleSigningSlasher    0x88A4c203C488E8277f583942672E1aF77e2B5040 0xF06EF728067dd7b5CC752DC0C787dABECcBfC82e 1.1.1.0 0         0         0         0         
 DowntimeSlasher         0xf2224c1d7b447D9A43a98CBD82FCCC0eF1c11CC5 0xdF3d2CD57090B3B6C15c18Ec7C1E33DCF565B449 2.0.0.0 0         0         0         0         
 Election                0x1c3eDf937CFc2F6F51784D20DEB1af1F9a8655fA 0x2a39E41a736D3d6d8b7C393397969BaAc8E53DC9 1.1.3.0 0         0         0         0         
 EpochRewards            0xB10Ee11244526b94879e1956745bA2E35AE2bA20 0xd894682B96B1E5954223e0554afad14b2a93cDdb 1.1.1.0 0         0         0         0         
 Escrow                  0xb07E10c5837c282209c6B9B3DE0eDBeF16319a37 0xa34117B48313dE0093d599720998415bAb5FD61d 1.2.0.0 2.195e+18 1.784e+21 9.053e+19 0         
 Exchange                0x17bc3304F94c85618c46d0888aA937148007bD3C 0x8070f183662d577Ab258d81eA18723EDece53F54 1.2.0.0 0         5.000e+16 0         0         
 ExchangeBRL             0xf391DcaF77360d39e566b93c8c0ceb7128fa1A08 0xEB80459DFb30594d501d459D6bDFFC4DE6840F20 1.2.0.0 0         0         0         0         
 ExchangeEUR             0x997B494F17D3c49E66Fafb50F37A972d8Db9325B 0xE20cf87413917D9751BFCDa9b88B8D758f75777e 1.2.0.0 0         0         0         0         
 FederatedAttestations   0x70F9314aF173c246669cFb0EEe79F9Cfd9C34ee3 0x926E88a280902Bfff5047693B9CeAfdb9F4d5095 1.1.0.0 0         0         0         0         
 FeeCurrencyWhitelist    0xB8641365dBe943Bc2fb6977e6FBc1630EF47dB5a 0x8DE5E4c86284F46a4b034a2F9a41A6175523daa9 NONE    0         0         0         0         
 FeeHandler              0xEAaFf71AB67B5d0eF34ba62Ea06Ac3d3E2dAAA38 0x31788a65f0e8318d6b2A36B9dE5Dfc4D1C22F182 1.1.0.0 1.916e+21 3.443e+18 2.700e+17 1.192e+19 
 Freezer                 0xfe0Ada6E9a7b782f55750428CC1d8428Cd83C3F1 0x423A32Ee1AF793DF26c4aEe7e36441C00C29e280 NONE    0         0         0         0         
 GasPriceMinimum         0xd0Bf87a5936ee17014a057143a494Dc5C5d51E5e 0x31b1Da7073576A3EdC402607B87B4e95539D7FE5 1.2.0.0 0         0         0         0         
 GoldToken               0xF194afDf50B03e69Bd7D057c1Aa9e10c9954E4C9 0xec6aFE1065c98Fb16E60Cf7764b145bbDE7a2a6c 1.1.2.0 2.160e+20 3.402e+20 4.020e+20 0         
 Governance              0xAA963FC97281d9632d96700aB62A4D1340F9a28a 0x6b8Ea5A8790eF33421facA99D6855D6444766CF8 1.4.0.0 6.208e+23 4.660e+19 2.000e+24 2.000e+24 
 GrandaMento             0xEcf09FCD57b0C8b1FD3DE92D59E234b88938485B 0x574b52707FA5353AE05685010d22A7eDea71625C 1.1.0.1 1.000e+19 0         0         2.900e+20 
 LockedGold              0x6a4CC5693DC5BFA3799C699F3B941bA2Cb00c341 0xF7B828aB943759BF05355A5F4F13D516CD45B4Ee 1.1.3.0 2.298e+23 1.000e+19 0         0         
 MentoFeeHandlerSeller   0xae83C63B5FB50C353c8d23397bcC9dBf3a9837Ac 0x4ec74B45BCCc7f57F434BbFfaEa068f70637fC91 1.1.0.0 0         0         0         0         
 OdisPayments            0x645170cdB6B5c1bc80847bb728dBa56C50a20a49 0x72eAC1F0518213Ad405560eFd3fB647FbDAdb703 1.1.0.0 0         1.059e+20 0         0         
 Random                  0xdd318EEF001BB0867Cd5c134496D6cF5Aa32311F 0x67c6829506DdF66Ed824Fd1cCC40665588Bc4631 1.1.1.0 0         0         0         0         
 Registry                0x000000000000000000000000000000000000ce10 0x33011E0a33AF1F757396f2a5A1F2158bEd179Dfd NONE    0         0         0         0         
 Reserve                 0xa7ed835288Aa4524bB6C73DD23c0bF4315D9Fe3e 0x315F17F403A7207ed090C80BbcFbdAF6c5d3CEDA 1.1.2.2 1.039e+26 1.000e+19 1.000e+19 0         
 SortedOracles           0xFdd8bD58115FfBf04e47411c1d228eCC45E93075 0xB07A33093d332f0D2810b36Bdd3c9e7390624F1F 1.1.2.1 3.200e+18 1.000e+17 0         0         
 StableToken             0x874069Fa1Eb16D44d622F2e0Ca25eeA172369bC1 0x555a4D35328462bCadFD9558295F8E0C98FEdea0 1.2.1.0 1.930e+20 7.013e+20 2.910e+20 3.875e+19 
 StableTokenBRL          0xE4D517785D091D3c54818832dB6094bcc2744545 0x73F93dcc49cB8A239e2032663e9475dd5ef29A08 1.2.1.0 1.550e+19 3.035e+19 3.025e+19 5.000e+17 
 StableTokenEUR          0x10c892A6EC43a53E45D0B916B4b7D383B1b78C0F 0x0B8d1BFdD9F67cdbab70D48C073d39aaf579f69C 1.2.1.0 8.700e+19 1.321e+20 1.620e+20 5.000e+18 
 UniswapFeeHandlerSeller 0xc7b6E77C3702666DDa8EB5b7F30234B020788b21 0x1365f75d7087D997F504f56f2CA60418d9970163 1.1.0.0 0         0         0         0         
 Validators              0x9acF2A99914E083aD0d610672E93d14b0736BBCc 0xF17D8624e0c3402D02b6F8D5870Fff0Dd35e4f0B 1.2.0.5 0         0         0         0         
 ```

2023-11-29 12:49 UTC, philbow61 commented
> ~On celocli v3.1.0, it actually looks like multiple proxy/implementation addresses are incorrect.~
> 
> Edit: My bad, at first I didn't configure celocli correctly. I mistakently compared the output for alfajores with addresses for mainnet.
> 
> Here are the RPC URLs for mainnet, alfajores, baklava: https://docs.celo.org/network/node/forno
> 
> ## Baklava
> I can reproduce the error. On Baklava, the command throws an error:
> 
> ```shell
> ~  $ celocli config:set --node=https://baklava-forno.celo-testnet.org  
> ~  $ celocli network:contracts                                        
>     Error: execution reverted
> ```
> 
> I'm using this website to compare: https://dhutch-test.celo-networks-dev.org/
> 
> According to the [website](https://dhutch-test.celo-networks-dev.org/), the FeeHandler address is indeed `0x0000000000000000000000000000000000000001` on Baklava:
> 
> <img alt="image" width="650" src="https://private-user-images.githubusercontent.com/46296830/286594782-f1ead6ce-59ec-4ad6-824d-05fc2f1a8720.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjIwOTcsIm5iZiI6MTcwMTI2MTc5NywicGF0aCI6Ii80NjI5NjgzMC8yODY1OTQ3ODItZjFlYWQ2Y2UtNTllYy00YWQ2LTgyNGQtMDVmYzJmMWE4NzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEyNDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2N2NlODk5MGFkNmNiYjZhNDE4MDM1ZTU0ZGE2N2Q2MDM4NDM2OTk4M2VhNmNiNjM5NWMxNGM1ZTc5NzYwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uC6lNMT4ak11D5xWKDHOz005tgktAv6DMNTOFQ5PJoU">
> ## Alfajores
> ```shell
> ~  $ celocli config:set --node=https://alfajores-forno.celo-testnet.org
> ~  $ celocli network:contracts                                          
>  Contract                Proxy                                      Implementation                             Version CELO      cUSD      cEUR      cREAL     
>  ─────────────────────── ────────────────────────────────────────── ────────────────────────────────────────── ─────── ───────── ───────── ───────── ───────── 
>  Accounts                0xed7f51A34B4e71fbE69B3091FcF879cD14bD73A9 0x133D9408098b72a18B6c79f06BC62965D1B59cC1 1.1.4.1 2.000e+19 2.000e+19 1.000e+19 0         
>  Attestations            0xAD5E5722427d79DFf28a4Ab30249729d1F8B4cc0 0xA758e8f4f79AB72184914343CaAb2E2162fdDd3D 1.2.0.0 0         2.134e+21 0         0         
>  BlockchainParameters    0xE5aCbb07b4Eed078e39D50F66bF0c80cF1b93abe 0x029d8a20D86157F47CcbEE5209DEe0591dD2eB70 1.3.0.0 0         0         0         0         
>  DoubleSigningSlasher    0x88A4c203C488E8277f583942672E1aF77e2B5040 0xF06EF728067dd7b5CC752DC0C787dABECcBfC82e 1.1.1.0 0         0         0         0         
>  DowntimeSlasher         0xf2224c1d7b447D9A43a98CBD82FCCC0eF1c11CC5 0xdF3d2CD57090B3B6C15c18Ec7C1E33DCF565B449 2.0.0.0 0         0         0         0         
>  Election                0x1c3eDf937CFc2F6F51784D20DEB1af1F9a8655fA 0x2a39E41a736D3d6d8b7C393397969BaAc8E53DC9 1.1.3.0 0         0         0         0         
>  EpochRewards            0xB10Ee11244526b94879e1956745bA2E35AE2bA20 0xd894682B96B1E5954223e0554afad14b2a93cDdb 1.1.1.0 0         0         0         0         
>  Escrow                  0xb07E10c5837c282209c6B9B3DE0eDBeF16319a37 0xa34117B48313dE0093d599720998415bAb5FD61d 1.2.0.0 2.195e+18 1.784e+21 9.053e+19 0         
>  Exchange                0x17bc3304F94c85618c46d0888aA937148007bD3C 0x8070f183662d577Ab258d81eA18723EDece53F54 1.2.0.0 0         5.000e+16 0         0         
>  ExchangeBRL             0xf391DcaF77360d39e566b93c8c0ceb7128fa1A08 0xEB80459DFb30594d501d459D6bDFFC4DE6840F20 1.2.0.0 0         0         0         0         
>  ExchangeEUR             0x997B494F17D3c49E66Fafb50F37A972d8Db9325B 0xE20cf87413917D9751BFCDa9b88B8D758f75777e 1.2.0.0 0         0         0         0         
>  FederatedAttestations   0x70F9314aF173c246669cFb0EEe79F9Cfd9C34ee3 0x926E88a280902Bfff5047693B9CeAfdb9F4d5095 1.1.0.0 0         0         0         0         
>  FeeCurrencyWhitelist    0xB8641365dBe943Bc2fb6977e6FBc1630EF47dB5a 0x8DE5E4c86284F46a4b034a2F9a41A6175523daa9 NONE    0         0         0         0         
>  FeeHandler              0xEAaFf71AB67B5d0eF34ba62Ea06Ac3d3E2dAAA38 0x31788a65f0e8318d6b2A36B9dE5Dfc4D1C22F182 1.1.0.0 1.917e+21 3.443e+18 2.712e+17 1.193e+19 
>  Freezer                 0xfe0Ada6E9a7b782f55750428CC1d8428Cd83C3F1 0x423A32Ee1AF793DF26c4aEe7e36441C00C29e280 NONE    0         0         0         0         
>  GasPriceMinimum         0xd0Bf87a5936ee17014a057143a494Dc5C5d51E5e 0x31b1Da7073576A3EdC402607B87B4e95539D7FE5 1.2.0.0 0         0         0         0         
>  GoldToken               0xF194afDf50B03e69Bd7D057c1Aa9e10c9954E4C9 0xec6aFE1065c98Fb16E60Cf7764b145bbDE7a2a6c 1.1.2.0 2.160e+20 3.402e+20 4.020e+20 0         
>  Governance              0xAA963FC97281d9632d96700aB62A4D1340F9a28a 0x6b8Ea5A8790eF33421facA99D6855D6444766CF8 1.4.0.0 6.208e+23 4.660e+19 2.000e+24 2.000e+24 
>  GrandaMento             0xEcf09FCD57b0C8b1FD3DE92D59E234b88938485B 0x574b52707FA5353AE05685010d22A7eDea71625C 1.1.0.1 1.000e+19 0         0         2.900e+20 
>  LockedGold              0x6a4CC5693DC5BFA3799C699F3B941bA2Cb00c341 0xF7B828aB943759BF05355A5F4F13D516CD45B4Ee 1.1.3.0 2.298e+23 1.000e+19 0         0         
>  MentoFeeHandlerSeller   0xae83C63B5FB50C353c8d23397bcC9dBf3a9837Ac 0x4ec74B45BCCc7f57F434BbFfaEa068f70637fC91 1.1.0.0 0         0         0         0         
>  OdisPayments            0x645170cdB6B5c1bc80847bb728dBa56C50a20a49 0x72eAC1F0518213Ad405560eFd3fB647FbDAdb703 1.1.0.0 0         1.059e+20 0         0         
>  Random                  0xdd318EEF001BB0867Cd5c134496D6cF5Aa32311F 0x67c6829506DdF66Ed824Fd1cCC40665588Bc4631 1.1.1.0 0         0         0         0         
>  Registry                0x000000000000000000000000000000000000ce10 0x33011E0a33AF1F757396f2a5A1F2158bEd179Dfd NONE    0         0         0         0         
>  Reserve                 0xa7ed835288Aa4524bB6C73DD23c0bF4315D9Fe3e 0x315F17F403A7207ed090C80BbcFbdAF6c5d3CEDA 1.1.2.2 1.039e+26 1.000e+19 1.000e+19 0         
>  SortedOracles           0xFdd8bD58115FfBf04e47411c1d228eCC45E93075 0xB07A33093d332f0D2810b36Bdd3c9e7390624F1F 1.1.2.1 3.200e+18 1.000e+17 0         0         
>  StableToken             0x874069Fa1Eb16D44d622F2e0Ca25eeA172369bC1 0x555a4D35328462bCadFD9558295F8E0C98FEdea0 1.2.1.0 1.930e+20 7.013e+20 2.910e+20 3.875e+19 
>  StableTokenBRL          0xE4D517785D091D3c54818832dB6094bcc2744545 0x73F93dcc49cB8A239e2032663e9475dd5ef29A08 1.2.1.0 1.550e+19 3.035e+19 3.025e+19 5.000e+17 
>  StableTokenEUR          0x10c892A6EC43a53E45D0B916B4b7D383B1b78C0F 0x0B8d1BFdD9F67cdbab70D48C073d39aaf579f69C 1.2.1.0 8.700e+19 1.321e+20 1.620e+20 5.000e+18 
>  UniswapFeeHandlerSeller 0xc7b6E77C3702666DDa8EB5b7F30234B020788b21 0x1365f75d7087D997F504f56f2CA60418d9970163 1.1.0.0 0         0         0         0         
>  Validators              0x9acF2A99914E083aD0d610672E93d14b0736BBCc 0xF17D8624e0c3402D02b6F8D5870Fff0Dd35e4f0B 1.2.0.5 0         0         0         0         
> ```
> 
> ## Mainnet
> ```shell
> ~  $ celocli config:set --node=https://forno.celo.org                                                                                                                
> ~  $ celocli network:contracts                                                                                                                                       
>  Contract                Proxy                                      Implementation                             Version CELO      cUSD      cEUR      cREAL           
>  ─────────────────────── ────────────────────────────────────────── ────────────────────────────────────────── ─────── ───────── ───────── ───────── ─────────       
>  Accounts                0x7d2168 [...]

2023-11-29 12:58 UTC, merged

2023-11-29 14:18 UTC, 0xarthurxyz commented
Pasting context from @martinvol from [Slack](https://celo-org.slack.com/archives/CP5V8KF51/p1701263761113139?thread_ts=1701258767.298679&cid=CP5V8KF51) for future reference:

> yes, baklava was a early release before the audit
> I’m currently working on updating it
> IMO cli shouldn’t have broken in that case, it should not assume there’s a Proxy in the core contracts

2023-11-29 14:23 UTC, 0xarthurxyz commented
We'll deal with the bug that gave rise to the FeeHandler related error here: 
- [celocli shouldn't break when core contract doesn't have a proxy#4](https://github.com/celo-org/developer-tooling/issues/4)

2023-11-29 19:59 UTC, 0xarthurxyz commented
For future reference: your changes are released in @celo/celocli@3.1.1

Release:
- https://github.com/celo-org/celo-monorepo/pull/10776#event-11099202136