[WIP] make page / baklava
celo-org/celo-monorepo pull request #1634
Opened 2019-11-08 13:34 UTC by diminator

### Description

Implements the leaderboard page for the great celo stake off according to [wireframe](https://figma.com/file/HzDfZq4jvFNgUvPuPmeC80Ss/Website-3.0?node-id=1919%3A0)

### Tested

![stakeoff-web-invert](https://user-images.githubusercontent.com/6178597/68480159-7011ef80-0234-11ea-96c9-eac21a5bb032.gif)

Upon loading:
![stakeoff-web-loading](https://user-images.githubusercontent.com/6178597/68480175-7738fd80-0234-11ea-8943-6727397af43e.gif)

Upon fetch error:
![stakeoff-web-error](https://user-images.githubusercontent.com/6178597/68480195-828c2900-0234-11ea-8319-34a863ed6fa7.png)

### Other changes

- An ENV var `REACT_APP_WS_GRAPHQL` needs to be passed to the app config

### Related issues

- Fixes #1630 

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

2019-11-08 13:38 UTC, diminator commented
@aaronmgdr @cmcewen @cla-bel 

This is only the top section with the leaderboard, not the subsequent sections with additional info.

Also to be checked is the namespace. Shall everything go under `Make`?

2019-11-08 18:19 UTC, aaronmgdr commented on packages/web/package.json
> +    "node-fetch": "^2.6.0",
we have "cross-fetch" which can be used isomorphically

2019-11-08 18:27 UTC, aaronmgdr commented
Hi its great that you implemented the fetching of data for leaderboard!. 
I have a branch at https://github.com/celo-org/celo-monorepo/tree/aaronmgdr/build4 which handles the rest of the page and a version of leaderboard with fake data

2019-11-08 18:29 UTC, aaronmgdr commented on packages/web/src/baklava/LeaderBoard.tsx
> +const graphqlURI = getenv('REACT_APP_WS_GRAPHQL', 'http://localhost:8080/v1/graphql')
this can be placed in env-config file and loaded with with getConfig from next/config

2019-11-08 18:30 UTC, aaronmgdr commented on packages/web/src/baklava/LeaderBoardView.tsx
> +          transform: 'scaleX(0)',
nice

2019-11-14 01:23 UTC, aaronmgdr requested changes
In case this gets lost and i forget

Requesting that node-fetch be replaced with the existing cross-fetch and that ENV vars are placed in env-config.js and gotten with getConfig from next/config

2019-12-09 18:22 UTC, closed without merging