Added network:head command to dump some useful info
celo-org/celo-monorepo pull request #2463
Opened 2020-01-17 05:39 UTC by yourcodesucks

### Description

Added network:head command to dump some useful info

Sample output:

```
timestamp: Fri, 17 Jan 2020 05:37:09 GMT
block number: 107665
epoch index: 149
epoch position: 385
block signer: 0xea0c8e8b18bdE45819483a4D8E64A5e94c4303Cc
```

### Tested

Ran against baklava network by building against the baklava branch on the following environment:

- osx 10.15.2
- yarn 1.21.0, 
- npm 6.11.3
- nodejs v10.17.0

2020-05-01 21:42 UTC, yorhodes requested changes
would be great to clean this up and get it merged

2020-05-01 21:42 UTC, yorhodes commented on packages/cli/src/commands/network/head.ts
> +    interesting['epoch index'] = Math.floor(block.number / 720) // TODO: epoch block duration should come from network:parameters
you can get this from `this.kit`
see how `network/parameters.ts` works

2020-05-01 21:42 UTC, yorhodes commented on packages/cli/src/commands/network/head.ts
> +    console.log(block.miner)
remove

2020-11-07 03:37 UTC, barbaraliau commented
Is this still a relevant PR or should this be closed?

2021-01-27 13:47 UTC, closed without merging