Etherbase e2e tests
celo-org/celo-monorepo pull request #2529
Opened 2020-01-24 06:48 UTC by lucasege

### Description

Sister PR to https://github.com/celo-org/celo-blockchain/issues/738 

Changes use of `etherbase` to `validator` and `tx-fee-recipient` in a backwards compatible way.

### Tested

Ran e2e tests

### Related issues

- Fixes https://github.com/celo-org/celo-blockchain/issues/738

### Backwards compatibility

Yes

2020-01-24 19:41 UTC, asaj requested changes

2020-01-24 19:41 UTC, asaj commented on packages/celotool/src/e2e-tests/transfer_tests.ts
> +        validator: validatorAddress,
It doesn't look like we're testing proposer transaction fees can be sent to a different address, can we set `txFeeRecipient` here as well?

2020-08-05 22:05 UTC, nategraf commented
@lucasege Does this PR need to be merged still?

2020-11-07 03:40 UTC, barbaraliau commented
Closing as this PR has become stale. Please feel free to reopen with updates if it is still relevant!

2020-11-07 03:40 UTC, closed without merging