Update validator group voting docs
celo-org/celo-monorepo pull request #4948
Opened 2020-09-02 15:06 UTC by pranaymohan

### Description

Made updates to make it clearer how to vote for Foundation vote recipients

2020-09-02 15:06 UTC, pranaymohan commented on packages/docs/celo-holder-guide/voting-validators.md
> +As described above, there are many criteria to consider when deciding which group to vote for. While it is highly recommended that all CELO holders do their indepednent research when deciding which g
```suggestion
As described above, there are many criteria to consider when deciding which group to vote for. While it is highly recommended that all CELO holders do their indepedent research when deciding which group to vote for, another option is to vote for Validator Groups that have received votes from the Celo Foundation.
```

2020-09-04 00:13 UTC, timmoreton requested changes
minor nits

2020-09-04 00:13 UTC, timmoreton commented on packages/docs/celo-holder-guide/voting-validators.md
> +# Voting for Validator Groups
Note this is ignored... it takes the title from the SUMMARY.md file. if you change it there, you'll need to also add redirects.

2020-09-04 00:13 UTC, timmoreton commented on packages/docs/celo-holder-guide/voting-validators.md
> +The Celo community makes these decisions by locking CELO tokens and voting for [Validator Groups](../celo-codebase/protocol/proof-of-stake/validator-groups.md), intermediaries that sit between voters
```suggestion
The Celo community makes these decisions by locking CELO and voting for [Validator Groups](../celo-codebase/protocol/proof-of-stake/validator-groups.md), intermediaries that sit between voters and Validators. Every Validator Group has an ordered list of up to 5 candidate Validators. Some organizations may operate a group with their own Validators in it; some may operate a group to which they have added Validators run by others.
```

2020-09-04 00:13 UTC, timmoreton commented on packages/docs/celo-holder-guide/voting-validators.md
> +Unlike a number of Proof of Stake protocols, **CELO used for voting is never at risk and will never be [slashed](../glossary.md#slashing)**. The actions of the Validator Groups or Validators you vote
```suggestion
Unlike a number of Proof of Stake protocols, **CELO used for voting is never at risk**. The actions of the Validator Groups or Validators you vote for can cause you to receive lower or higher rewards, but the CELO you locked will always be available to be unlocked in the future. [Slashing](../glossary.md#slashing) in the Celo protocol applies only to Validators and Validator Groups. 
```

2020-09-04 00:13 UTC, timmoreton commented on packages/docs/celo-holder-guide/voting-validators.md
> +As described above, there are many criteria to consider when deciding which group to vote for. While it is highly recommended that all CELO holders do their indepedent research when deciding which gr
```suggestion
As described above, there are many criteria to consider when deciding which group to vote for. While it is highly recommended that all CELO holders do their independent research when deciding which group to vote for, another option is to vote for Validator Groups that have received votes from the Celo Foundation.
```

2020-09-04 00:13 UTC, timmoreton commented on packages/docs/celo-holder-guide/voting-validators.md
> +It can be helpful on validator explorers to learn more about validators and validator groups when deciding which group to vote for. to rely on The Celo ecosystem includes a number of great services f
```suggestion
The Celo ecosystem includes a number of great services for browsing registered Validator Groups and Validators.
```

2020-09-08 23:16 UTC, timmoreton approved these changes

2020-11-03 23:29 UTC, merged