KomenciKit - Client-side un/blinding
celo-org/celo-monorepo pull request #5659
Opened 2020-11-02 04:19 UTC by codyborn

### Description

Keep phone number secure by performing un/blinding on the Valora-side. This keeps the phone number mapping private, preventing Komenci from viewing the association.

### Tested

Unit tests

### Backwards compatibility

Not backward compatible, but it's not currently in use.

2020-11-02 16:59 UTC, bowd requested changes

2020-11-02 16:59 UTC, bowd commented on packages/komencikit/src/actions.ts
> +  base64BlindedMessage: string
On Komenci's side you called this `blindedPhoneNumber` - not sure which one makes more sense but I think we should keep only one 😅

2020-11-02 16:59 UTC, bowd commented on packages/komencikit/src/kit.ts
> +    blsBlindingClient: BlsBlindingClient
I'm wondering whether it's a bit cleaner from the Valora perspective to just pass in the ODIS_PUB_KEY as an option to the constructor and construct the blinding client inside of komencikit :-/

Taking it as a param to this function is also a bit more composable in a sense. In the sense that I imagine `BlsBlindingClient` as a thin-ish interface that can be implemented in multiple ways and passed in.

2020-11-02 22:47 UTC, codyborn commented on packages/komencikit/src/actions.ts
> +  base64BlindedMessage: string
Good catch!

2020-11-02 22:59 UTC, codyborn commented on packages/komencikit/src/kit.ts
> +    blsBlindingClient: BlsBlindingClient
Yeah, that's possible. The same BlsBlindingClient instance needs to be re-used for the unblinding (it's potentially stateful) so we'd have to make KomenciKit stateful as well which introduces more complexity. As we discussed in the sync today, Valora uses the ReactBlsBlindingClient while vanilla typescript uses the WasmBlsBlindingClient so it's easier to have the caller decide which client to use.

2020-11-03 07:14 UTC, bowd commented on packages/komencikit/src/kit.ts
> +    blsBlindingClient: BlsBlindingClient
Yup I was split from the get-go but after we talked about it during the sync it did make more sense to pass that in here :+1:

2020-11-03 07:14 UTC, bowd approved these changes

2020-11-04 01:45 UTC, merged