[ContractKit]Add code to enable local signing of transactions
celo-org/celo-monorepo pull request #729
Opened 2019-08-27 02:26 UTC by ashishb

### Description

Add code to enable local signing of transactions. Most of the code has been ported over from the walletkit. Note that the test interacts with an `integration` node since Ganache does not support our modified transaction structure.

### Tested

`$ jest src/utils/tx-signing.test.ts`

### Related issues

- Partially addresses #477

2019-08-27 19:02 UTC, mcortesi requested changes

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/web3-utils.ts
> +export class Web3Utils {
Don't use class + static methods for namespacing. Not what any js developer would use/expect.

export functions directly

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/web3-utils.ts
> +  static async getWeb3(protocol: string, ipAddress: string, port: number): Promise<Web3> {
don't split the url in 3 vars. People usually have one config variable for the url, not 3

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/web3-utils.ts
> +  static async getWeb3(protocol: string, ipAddress: string, port: number): Promise<Web3> {
rename to `newWeb`. In fact there is one in `index.ts`

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/web3-utils.ts
> +  static async getWeb3WithSigningAbility(web3: Web3, privateKey: string): Promise<Web3> {
I'd rather find another name for this...
`new...` and then maybe `LocalWeb3`?

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/web3-utils.ts
> +  private _provider: any
don't use any

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/web3-utils.ts
> +    debug(`WrappingSubprovider@handleRequest: ${JSON.stringify(payload)}`)
bad use of `debug()`. Read the docs, it has `printf` style markers to construct a string. This avoid extra work when debugging is disabled

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/web3-utils.ts
> +        debug(`WrappingSubprovider@response is error: ${err}`)
same

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/web3-utils.ts
> +      debug(`WrappingSubprovider@response: ${JSON.stringify(response)}`)
same

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/web3-utils.ts
> +        debug(`WrappingSubprovider@response includes error: ${JSON.stringify(response)}`)
same

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/utils-test.ts
> +export async function getWeb3WithSigningAbilityForTesting(
why this? it doesn't do anything

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/web3-utils.ts
> +  static async getWeb3WithSigningAbility(web3: Web3, privateKey: string): Promise<Web3> {
no need to make it async

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/web3-utils.ts
> +  static async getWeb3(protocol: string, ipAddress: string, port: number): Promise<Web3> {
no need to make it async... please check signatures

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/utils-test.ts
> +  // @ts-ignore-next-line
better to use `any` where it's need that ignore the whole line

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/tx-signing.ts
> +  debug(`getRawTransaction@Signing: Signed transaction ${JSON.stringify(signedTransaction)}`)
use printf style

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/tx-signing.ts
> +export async function getRawTransaction(
10 positional parameters!
very hard to read!!!

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/tx-signing.ts
> +export async function getRawTransaction(
use an object

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/tx-signing.ts
> +    debug(`signTransactionAsync: txParams are ${JSON.stringify(txParams)}`)
same

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/tx-signing.ts
> +    const signedTx: any = await signTransaction(txParams, this._celoPrivateKey)
can we avoid any?

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/tx-signing.test.ts
> +const randomIp = 'http://127.0.0.1:8545'
we can't really merge this.

2019-08-27 19:02 UTC, mcortesi commented on packages/contractkit/src/utils/tx-signing.test.ts
> +      const amountInWei = new BigNumber(1e18)
unsafe!
https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Number/MAX_SAFE_INTEGER

Use `Web3.utilt.toWei`

2019-08-27 19:59 UTC, ashishb commented on packages/contractkit/src/utils/web3-utils.ts
> +export class Web3Utils {
Done.

2019-08-27 19:59 UTC, ashishb commented on packages/contractkit/src/utils/web3-utils.ts
> +  static async getWeb3(protocol: string, ipAddress: string, port: number): Promise<Web3> {
Removed this code completely.

2019-08-27 19:59 UTC, ashishb commented on packages/contractkit/src/utils/web3-utils.ts
> +  static async getWeb3(protocol: string, ipAddress: string, port: number): Promise<Web3> {
Given the existing one. I removed this one.

2019-08-27 20:00 UTC, ashishb commented on packages/contractkit/src/utils/web3-utils.ts
> +  static async getWeb3WithSigningAbility(web3: Web3, privateKey: string): Promise<Web3> {
How about `addSigningAbilityToWeb3`? This code is modifying the existing web3 object.

2019-08-27 20:42 UTC, ashishb commented on packages/contractkit/src/utils/tx-signing.ts
> +export async function getRawTransaction(
Changed to use `CeloTx`

2019-08-27 20:44 UTC, ashishb commented on packages/contractkit/src/utils/tx-signing.ts
> +    const signedTx: any = await signTransaction(txParams, this._celoPrivateKey)
Removed `any`. The object being returned is a custom one. Should I create a class for it?

2019-08-27 20:47 UTC, ashishb commented on packages/contractkit/src/utils/tx-signing.test.ts
> +      const amountInWei = new BigNumber(1e18)
This unsafe code was only in the test code but changed to 
```
const amountInWei = Web3.utils.toWei('1', 'ether')
const gasFees = Web3.utils.toWei('1', 'mwei')
```

2019-08-27 21:10 UTC, ashishb commented on packages/contractkit/src/utils/tx-signing.test.ts
> +const randomIp = 'http://127.0.0.1:8545'
Removed. Since I don't really care about the signer, I can change it to use Ganache as well for now.

2019-08-27 22:12 UTC, ashishb commented on packages/contractkit/src/utils/web3-utils.ts
> +  private _provider: any
Changed to use `Provider`

I could not find a way to instantiate 
```
interface Callback<ResultType> {
  (error: Error): void;
  (error: null, val: ResultType): void;
}
```

So, I had to add `// @ts-ignore-next-line` before
    `return this._provider.send(payload, (err: Error, response: JSONRPCResponsePayload) => {`

2019-08-28 14:19 UTC, mcortesi commented on packages/contractkit/src/utils/web3-utils.ts
> +  static async getWeb3WithSigningAbility(web3: Web3, privateKey: string): Promise<Web3> {
maybe `addLocalAccount`

2019-08-28 14:23 UTC, mcortesi commented on packages/contractkit/src/utils/web3-utils.ts
> +  private _provider: any
probably because of incorrect typing; you don't need ts-ignore

`(err: Error, response: JSONRPCResponsePayload)` is not a valid callback:

  1. err can be null
  2. response is optional.

You can try:
`(err: null | Error, response?: JSONRPCResponsePayload)`

but maybe it won't work like that...  if not do a little research on how properly type is...

another idea... don't specify types in the signature, and add a `as Callback<JSONRPCResponsePayload>` to the end

2019-08-28 14:38 UTC, mcortesi requested changes

2019-08-28 14:38 UTC, mcortesi commented on packages/contractkit/src/utils/signing-utils.ts
> +import { account as Account, bytes as Bytes, hash as Hash, nat as Nat, RLP } from 'eth-lib'
CHECK all imports... neither of these are in the package.json!

2019-08-28 14:38 UTC, mcortesi commented on packages/contractkit/src/utils/signing-utils.ts
> +import { extend, isNull, isUndefined } from 'lodash'
don't include lodash. It's a big dependency, for a couple of method that are really easy to implement, even inline

2019-08-28 14:38 UTC, mcortesi commented on packages/contractkit/src/utils/signing-utils.ts
> +import * as helpers from 'web3-core-helpers'
not in package.json

2019-08-28 14:38 UTC, mcortesi commented on packages/contractkit/src/utils/signing-utils.ts
> +function isNot(value: any) {
inline this with a `== null` (only 2 =)

2019-08-28 14:38 UTC, mcortesi commented on packages/contractkit/src/utils/signing-utils.ts
> +  debug(`signing-utils@recoverTransaction: values are ${values}`)
use printf notation

2019-08-28 14:38 UTC, mcortesi commented on packages/contractkit/src/utils/tx-signing.test.ts
> +const accountAddress = generateAccountAddressFromPrivateKey(privateKey)
it would be nice for kit to provide an `Account` abstraction.. or maybe `LocalAccount`...

ether.js or even web3 has this concept. we should use it...

2019-08-28 14:38 UTC, mcortesi commented on packages/contractkit/src/utils/tx-signing.test.ts
> +function closeConnection(provider: Provider) {
is this really needed?

2019-08-28 14:38 UTC, mcortesi commented on packages/contractkit/src/utils/tx-signing.ts
> +export interface CeloPartialTxParams extends PartialTxParams {
isn't this better expressed as:
`type PartialCeloTx = Partial<CeloTx>`

2019-08-28 14:38 UTC, mcortesi commented on packages/contractkit/src/utils/tx-signing.ts
> +  private static getPrivateKeyWithout0xPrefix(privateKey: string) {
why a static method?

2019-08-28 14:38 UTC, mcortesi commented on packages/contractkit/src/utils/tx-signing.ts
> +  private readonly _celoPrivateKey: string // Always 0x prefixed
no need to use `_`. That's an idiom in js, not in ts

2019-08-28 14:38 UTC, mcortesi commented on packages/contractkit/src/utils/tx-signing.ts
> +      debug(`getChainId chain result ID is ${this._chainId}`)
printf style

2019-08-28 14:38 UTC, mcortesi commented on packages/contractkit/src/utils/utils-test.ts
> +import Web3 from 'web3'
there's a `test-utils` folder for all test related utility package. and it's ignored when we publish

2019-08-28 14:38 UTC, mcortesi commented on packages/contractkit/src/utils/utils-test.ts
> +export async function getWeb3WithSigningAbilityForTesting(
?

2019-08-28 16:23 UTC, ashishb commented on packages/contractkit/src/utils/web3-utils.ts
> +  static async getWeb3WithSigningAbility(web3: Web3, privateKey: string): Promise<Web3> {
Changed to `addLocalAccount`

2019-08-28 16:33 UTC, ashishb commented on packages/contractkit/src/utils/signing-utils.ts
> +  debug(`signing-utils@recoverTransaction: values are ${values}`)
Changed everywhere.

2019-08-28 16:43 UTC, ashishb commented on packages/contractkit/src/utils/signing-utils.ts
> +function isNot(value: any) {
Done. I think the original code which was taken from https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth-accounts/src/index.js was more clear though.

2019-08-28 16:44 UTC, ashishb commented on packages/contractkit/src/utils/tx-signing.test.ts
> +function closeConnection(provider: Provider) {
Removed. No point discussing pure test code.

2019-08-28 16:45 UTC, ashishb commented on packages/contractkit/src/utils/tx-signing.ts
> +  private static getPrivateKeyWithout0xPrefix(privateKey: string) {
It does not rely on the state of `CeloProvider` class.

2019-08-28 16:45 UTC, ashishb commented on packages/contractkit/src/utils/tx-signing.ts
> +  private readonly _celoPrivateKey: string // Always 0x prefixed
Changed to `celoPrivateKey`

2019-08-28 16:46 UTC, ashishb commented on packages/contractkit/src/utils/tx-signing.ts
> +    debug(`signTransactionAsync: txParams are ${JSON.stringify(txParams)}`)
Changed to printf style.

2019-08-28 16:46 UTC, ashishb commented on packages/contractkit/src/utils/tx-signing.ts
> +      debug(`getChainId chain result ID is ${this._chainId}`)
Done

2019-08-28 16:46 UTC, ashishb commented on packages/contractkit/src/utils/tx-signing.ts
> +  debug(`getRawTransaction@Signing: Signed transaction ${JSON.stringify(signedTransaction)}`)
Done

2019-08-28 16:47 UTC, ashishb commented on packages/contractkit/src/utils/utils-test.ts
> +export async function getWeb3WithSigningAbilityForTesting(
My bad. This became hollow and should have been removed.

2019-08-28 16:54 UTC, ashishb commented on packages/contractkit/src/utils/utils-test.ts
> +  // @ts-ignore-next-line
This fails due to a weird `provider` not provided. I took this code from https://github.com/celo-org/celo-monorepo/blob/ashishb/contractkit_local_signing/packages/cli/src/commands/account/new.ts#L34 a few months back.

2019-08-28 16:54 UTC, ashishb commented on packages/contractkit/src/utils/web3-utils.ts
> +    debug(`WrappingSubprovider@handleRequest: ${JSON.stringify(payload)}`)
Changed to printf style

2019-08-28 16:55 UTC, ashishb commented on packages/contractkit/src/utils/web3-utils.ts
> +        debug(`WrappingSubprovider@response is error: ${err}`)
Fixed.

2019-08-28 16:55 UTC, ashishb commented on packages/contractkit/src/utils/web3-utils.ts
> +        debug(`WrappingSubprovider@response includes error: ${JSON.stringify(response)}`)
Fixed.

2019-08-28 16:55 UTC, ashishb commented on packages/contractkit/src/utils/web3-utils.ts
> +      debug(`WrappingSubprovider@response: ${JSON.stringify(response)}`)
Fixed.

2019-08-28 16:56 UTC, ashishb commented on packages/contractkit/src/utils/utils-test.ts
> +import Web3 from 'web3'
Not required anymore. I deleted this file.

2019-08-28 18:24 UTC, ashishb commented on packages/contractkit/src/utils/web3-utils.ts
> +  private _provider: any
Thanks
`(err: null | Error, response?: JsonRPCResponse` worked.

2019-08-28 18:48 UTC, ashishb commented on packages/contractkit/src/utils/signing-utils.ts
> +import { account as Account, bytes as Bytes, hash as Hash, nat as Nat, RLP } from 'eth-lib'
Added to package.json. The reason I didn't add this earlier is that I believe we use the version of this from `web3` package. I am not sure though.

2019-08-28 18:48 UTC, ashishb commented on packages/contractkit/src/utils/signing-utils.ts
> +import * as helpers from 'web3-core-helpers'
Added to package.json. The reason I didn't add this earlier is that I believe we use the version of this from `web3` package. I am not sure though.

2019-08-28 18:52 UTC, ashishb commented on packages/contractkit/src/utils/signing-utils.ts
> +import { extend, isNull, isUndefined } from 'lodash'
> It's a big dependency, for a couple of method that are really easy to implement, even inline

Thanks. I didn't know that. The original code referenced at https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth-accounts/src/index.js did it this way. I have removed it.

2019-08-28 19:08 UTC, ashishb commented on packages/contractkit/src/utils/tx-signing.ts
> +export interface CeloPartialTxParams extends PartialTxParams {
Co-incidentally since underlying Tx type is

```
export interface Tx {
	nonce?: string | number;
	chainId?: string | number;
	from?: string;
	to?: string;
	data?: string;
	value?: string | number;
	gas?: string | number;
	gasPrice?: string | number;
}
```

Since if it had a mandatory field then, `Partial<>` would make that optional as well.
I changed the code to `export type CeloPartialTxParams = Partial<CeloTx>`

2019-08-28 19:09 UTC, ashishb commented on packages/contractkit/src/utils/tx-signing.ts
> +export interface CeloPartialTxParams extends PartialTxParams {
Actually, digging further I differ

PartialTxParams is defined as
```
export interface PartialTxParams {
    nonce: string;
    gasPrice?: string;
    gas: string;
    to: string;
    from: string;
    value?: string;
    data?: string;
    chainId: number;
}
```
So, it does not have mandatory fields. Keeping the original code `export interface CeloPartialTxParams extends PartialTxParams {...`

2019-08-28 20:06 UTC, mcortesi commented on packages/contractkit/src/utils/signing-utils.ts
> +import { account as Account, bytes as Bytes, hash as Hash, nat as Nat, RLP } from 'eth-lib'
no problem. 
So, it probably works (compiles) because we have a mono repo and another package uses. But we should add all dependencies explicitely to pkg.json

2019-08-28 22:51 UTC, mcortesi commented on packages/contractkit/src/utils/signing-utils.ts
> +function isNull(value: any): boolean {
`isNull<A>(value: null | A): value is A`

2019-08-28 23:01 UTC, mcortesi approved these changes

2019-08-29 00:13 UTC, ashishb commented on packages/contractkit/src/utils/tx-signing.ts
> +  private static getPrivateKeyWithout0xPrefix(privateKey: string) {
Moved outside `CeloProvider` class.

2019-08-29 00:40 UTC, merged