Web based DApp tutorial
celo-org/celo-monorepo pull request #7327
Opened 2021-03-03 14:06 UTC by AlexBHarley

### Description

With the upcoming Make It Mobile hackathon we anticipate a large number of web based DApps being launched. This tutorial can serve as a kick starter for many teams looking to build on Celo.

2021-03-03 17:44 UTC, barbaraliau requested changes
This is great! I didn't run through the tutorial myself, but everything seemed clear and easy to follow.

Couple small changes (mainly typos), and then one linting error that needs to be resolved. Then this is G2G.

2021-03-03 17:44 UTC, barbaraliau commented on packages/docs/developer-resources/walkthroughs/web-dapp.md
> +Leveraging our previously added [@celo-tool/suse-contractkit](https://github.com/celo-tools/use-contractkit) library we can provide a button that prompts the user to connect their wallet.
typo: [@celo-tool/~s~use-contractkit]

2021-03-03 17:44 UTC, barbaraliau commented on packages/docs/developer-resources/walkthroughs/web-dapp.md
> +- [@celo-tools/use-contractkit](https://github.com/celo-tools/use-contractkit) is a community provided library to ease establishing the connection with a users wallet. When developing with this libra
Suggest adding: 
"...establishing the connection with a users wallet, whether that is a hardware wallet, mobile wallet, or web wallet."

"...[Valora](https://valoraapp.com/), a Ledger, Metamask and more"

2021-03-03 17:44 UTC, barbaraliau commented on packages/docs/developer-resources/walkthroughs/web-dapp.md
> +Here's how it looks Using a combination of the `useEffect` and `useCallback` hooks to request and display all dequeued proposals from the blockchain.
typo: "Here's how it looks ~U~using..."

2021-03-03 17:44 UTC, barbaraliau commented on packages/docs/developer-resources/walkthroughs/web-dapp.md
> +A prerequisite to [voting on Celo governance proposals](celo-owner-guide/voting-governance.md) is having locked Celo to vote with. We won't cover the various flows for locking, unlocking and relockin
Linter doesn't like this path to the file
from CI:
`194:19-194:95  warning  Link to unknown file: `celo-owner-guide/voting-governance.md`. Did you mean `../../celo-holder-guide/voting-governance.md`  missing-file  remark-validate-links`

2021-03-03 17:44 UTC, barbaraliau commented on packages/docs/developer-resources/walkthroughs/web-dapp.md
> +## Best practices
I love this section. We don't have to do this now, but I'd love to pull this out and have a Best Practices high-level section for reference outside of the tutorial.

2021-03-03 18:28 UTC, eelanagaraj commented on packages/docs/developer-resources/walkthroughs/web-dapp.md
> +- [@celo-tools/use-contractkit](https://github.com/celo-tools/use-contractkit) is a community provided library to ease establishing the connection with a users wallet. When developing with this libra
nit: "user's wallet"

2021-03-03 18:28 UTC, eelanagaraj commented on packages/docs/developer-resources/walkthroughs/web-dapp.md
> +### Connecting to the users wallet
nit: "user's wallet"

2021-03-03 18:34 UTC, eelanagaraj commented on packages/docs/developer-resources/walkthroughs/web-dapp.md
> +Take this advice with a grain of salt as it really depends on how proficient your users are. At some point in most DApp users are going to need to deal with large numbers. It's up to you whether you
maybe instead of "proficient" something like "familiar with [cryptocurrencies/blockchain] your users are"?

2021-03-03 18:35 UTC, eelanagaraj approved these changes, later dismissed
left a few comments but overall looks good to me!

2021-03-03 19:00 UTC, eelanagaraj commented on packages/docs/developer-resources/walkthroughs/web-dapp.md
> +- [@celo/contractkit](https://github.com/celo-org/celo-monorepo/tree/master/packages/sdk/contractkit) is a lightweight wrapper around the [Web3](https://web3js.readthedocs.io/) object you may alrady
typo: -> alrady

2021-03-03 19:11 UTC, eelanagaraj approved these changes
LGTM

2021-03-04 03:02 UTC, barbaraliau approved these changes
It good.

2021-03-04 03:02 UTC, merged