Condense, organize, fix dappkit usage docs
celo-org/celo-monorepo pull request #7385
Opened 2021-03-10 13:11 UTC by eelanagaraj

### Description
We had a lot of duplication across the dappkit README + the published DappKit docs. I did the following:
- moved all missing examples and text (including @gastonponti's awesome recent example) from the sdk/dappkit/README --> the `usage.md` which is published on our docs page, and linked these docs from the `README`. (Reason behind this: devs are more likely to be consumers of DAppKit and look in the published docs before the actual package README; even if devs see these docs on NPM, directing them to the wider breadth of Celo docs is probably a good idea in any case)
- added additional notes about dappkit-web and expo to the docs landing page (docs `README`, separate from sdk `README`)
- some nits/rewording, fixed broken links, etc.

Edit: ended up going back and fixing the previous snippets as most were broken.

### Tested
Feel free to check out what these published docs would look like [here (forked personal gitbook)](https://app.gitbook.com/@eela/s/forked-monorepo-docs-test/developer-guide/dappkit)

Merged Ponti's PR into this which fixes #7444

2021-03-15 15:19 UTC, critesjosh commented on packages/docs/developer-resources/dappkit/usage.md
> +const receipt = await tx0.waitReceipt();
since all of the `receipts` are `const`, they need to have different names
```suggestion
const receipt0 = await tx0.waitReceipt();
```

2021-03-15 15:19 UTC, critesjosh commented on packages/docs/developer-resources/dappkit/usage.md
> +const receipt = await tx1.waitReceipt();
```suggestion
const receipt1 = await tx1.waitReceipt();
```

2021-03-15 15:19 UTC, critesjosh commented on packages/docs/developer-resources/dappkit/usage.md
> +const receipt = await tx2.waitReceipt();
```suggestion
const receipt2 = await tx2.waitReceipt();
```

2021-03-15 15:20 UTC, critesjosh commented on packages/docs/developer-resources/dappkit/usage.md
> +const receipt = await tx3.waitReceipt();
```suggestion
const receipt3 = await tx3.waitReceipt();
```

2021-03-15 15:22 UTC, critesjosh commented
@eelanagaraj were you able to test the example code on a mobile device? i tried quickly with a previous dappkit example I was working on and ran into some errors, not sure if they are with the code example or the boilerplate I was starting with.

2021-03-15 15:51 UTC, eelanagaraj commented
@critesjosh that example came directly from a [recent PR](https://github.com/celo-org/celo-monorepo/pull/7346/files) so I actually didn't check this part on a mobile device (this PR was more intended to consolidate the location of all of the examples we had). That said, happy to make those suggested changes/double check this section!

2021-03-15 16:30 UTC, barbaraliau requested changes
LGTM, with the request to update to remove semi-colons and use single quotes for consistency. The majority of our docs and examples follow this style (though there are some stragglers out there).

2021-03-22 12:35 UTC, AlexBHarley approved these changes
LGTM! So nice to have better documentation

2021-03-24 16:35 UTC, barbaraliau approved these changes
This LGTM. Anything that stood out to me are small things and aren't enough to hold this up from being merged. Will create an issue for that instead.

2021-03-24 16:41 UTC, merged