Add reference to blog article
celo-org/celo-monorepo pull request #8142
Opened 2021-06-21 17:39 UTC by Creamers158

Nice addition to read about the cohorts and how they work. (Good visual/picture about how cohorts by Pranay)

### Description

The article gives a little more insight about the working and the use of cohorts. Good article need reference.

2021-06-21 20:21 UTC, barbaraliau requested changes
Thanks for opening this PR! Please see comment for requested changes.

2021-06-21 20:21 UTC, barbaraliau commented on packages/docs/validator-guide/celo-foundation-voting-policy.md
> +Additional details and explanation about cohorts can be found here [The-celo-foundation-voting-program](https://medium.com/celoorg/the-celo-foundation-voting-program-7ad9fd2e918d) in the Celo Blog ar
Suggested update for better sentence flow:

Additional details and explanation about cohorts and the [Celo Foundation Voting Program](https://medium.com/celoorg/the-celo-foundation-voting-program-7ad9fd2e918d) can be found on the Celo Blog.

2021-06-23 14:23 UTC, aslawson approved these changes
LGTM, thanks for the add!

2021-06-23 14:24 UTC, aslawson commented
Oh missed @barbaraliau's comment, please address that first 🙏

2021-06-24 16:51 UTC, Creamers158 commented
> Oh missed @barbaraliau's comment, please address that first 🙏

What am I missing here :) Think I already change it here: https://github.com/celo-org/celo-monorepo/pull/8142/commits/2bd2754c77d07b0287c42af74863f6cf3c245ef9

2023-01-10 17:59 UTC, closed without merging