cREAL on cli
celo-org/celo-monorepo pull request #9040
Opened 2021-12-03 10:01 UTC by martinvol

### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### Documentation

_The set of community facing docs that have been added/modified because of this change_

2021-12-07 15:56 UTC, martinvol commented on packages/env-tests/src/monorepoRun.ts
> +    // runGrandaMentoTest(context, stableTokensToTest)
```suggestion
    runOracleTest(context)
    runReserveTest(context)
    runAttestationTest(context)
    runGrandaMentoTest(context, stableTokensToTest)
```

2021-12-07 15:57 UTC, martinvol commented on packages/env-tests/src/monorepoRun.ts
> +const DEFAULT_TOKENS_TO_TEST = [StableToken.cREAL]
```suggestion
const DEFAULT_TOKENS_TO_TEST = [StableToken.cUSD]
```

2021-12-07 15:57 UTC, martinvol commented on packages/env-tests/src/tests/exchange.ts
> +        // console.log(exchange.address)
```suggestion
```

2021-12-07 15:57 UTC, martinvol commented on packages/env-tests/src/tests/exchange.ts
> +        // console.log("approve1")
```suggestion
```

2021-12-07 15:58 UTC, martinvol commented on packages/env-tests/src/tests/exchange.ts
> +        // console.log("approve2")
```suggestion
```

2021-12-07 18:07 UTC, nicolasbrugneaux commented on packages/sdk/contractkit/src/wrappers/StableToken.test.ts
> +      name: 'Celo Brazilian Rean',
typo
```suggestion
      name: 'Celo Brazilian Real',
```

2021-12-07 18:08 UTC, nicolasbrugneaux requested changes
Looks good aside  the typo

2021-12-07 18:34 UTC, m-chrzan approved these changes
Looks good overall. Is it too late to standardize on just one of cREAL vs cBRL throughout the repo?

2021-12-08 13:00 UTC, martinvol commented
It should be cREAL everywhere but in the contracts I left the StableTokenBRL (so that it can be directly mapped by the oracles -> CELO/BRL -> StableTokenBRL)

2021-12-08 13:06 UTC, nicolasbrugneaux approved these changes

2021-12-08 21:06 UTC, merged