Adding linux install steps, small re-org of contents and TOC
celo-org/celo-monorepo pull request #921
Opened 2019-09-11 12:39 UTC by aaitor

### Description

This change adds some additional documentation about how to install the repo requirements in Linux systems. Also add a small table of contents to help finding the contents in the document.

### Tested

All the commands added in the documentation were tested in Ubuntu 19.04

### Other changes

nope

### Related issues

- Fixes #920 

### Backwards compatibility

it doesn't apply

2019-09-11 16:27 UTC, drklee3 requested changes
Looks good! Just a few small comments

2019-09-11 16:27 UTC, drklee3 commented on SETUP.md
> +#### Install Android Dev Tools
android-sdk and android-platform-tools still use `brew` here, could be moved to the corresponding OS specific setup along with an Ubuntu version

2019-09-11 16:27 UTC, drklee3 commented on SETUP.md
>  Alternatively, you can install Genymotion, a nice emulator manager:
Same for genymotion, also uses `brew` and some OSX specific instructions

2019-09-12 09:42 UTC, aaitor commented on SETUP.md
> +#### Install Android Dev Tools
good point, adding linux info

2019-09-12 15:22 UTC, jmrossy reviewed
One issue but otherwise looks good, thanks!

2019-09-12 15:22 UTC, jmrossy commented on SETUP.md
> +brew cask install genymotion
Genymotion doesn't work with our e2e tests which is why we don't recommend it in our setup guide. Feel free to mention it as an alternative though.

2019-09-12 16:49 UTC, aaitor commented on SETUP.md
> +brew cask install genymotion
clarification added

2019-09-12 22:13 UTC, drklee3 approved these changes
LGTM!  Thanks @aaitor!

2019-09-13 10:17 UTC, jmrossy requested changes

2019-09-13 10:17 UTC, jmrossy commented on SETUP.md
> +Alternatively, you can install Genymotion, a nice emulator manager. It doesn't work with the e2e tests but could help during development.
Alternatively to what? Maybe this section was meant to be at the bottom next to the other emulator related instructions?

2019-09-15 10:04 UTC, aaitor commented
problem with non-existing remote fork, this PR is replaced by #1004

2019-09-15 10:04 UTC, closed without merging