Feature/mcmint bi pool manager
celo-org/celo-monorepo pull request #9851
Opened 2022-09-09 14:26 UTC by bowd

### Description

The BiPoolManager is the first implementation of an IExchangeManager, it handles 2-asset virtual pools, an immediate extension of Mento1. 

For more details on design see [the design doc](https://docs.google.com/document/d/1fII7pHpBqnlPtDXj0JdvAIAr6V5JZN5ZuJREYYCaww8/edit#heading=h.qjo0a6y2br5l).

Some todos that are left:
- [ ] Tests around bucket updates
- [ ] Bucket sizing caps

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### Documentation

_The set of community facing docs that have been added/modified because of this change_

2022-09-13 14:06 UTC, bayological requested changes

2022-09-13 14:06 UTC, bayological commented on packages/protocol/contracts/stability/interfaces/IExchangeManager.sol
>     * @param tokenOut The token to be bought
I couldn't add a comment to the line, but on line 7 the comment mentions 'listing manager' & 'TwoAssetPoolManager'. I think these may be leftovers from the design as they're not referenced anywhere else. Can we update the comment to reflect the current code?

2022-09-13 14:06 UTC, bayological commented on packages/protocol/contracts/stability/BiPoolManager.sol
> +    Pool memory pool = getPool(exchangeId);
The 'exchangeId' naming isn't consistent. I see this being problematic in the case of an error. When this function is called, if the pool/exchange is not found, the error message says "A pool with the specified id does not exist". This will be very confusing to consumers as they will have no knowledge of the poolID.

2022-09-13 14:06 UTC, bayological commented on packages/protocol/contracts/stability/BiPoolManager.sol
> +      reserve.isStableAsset(poolInfo.asset1) || reserve.isCollateralAsset(poolInfo.asset1),
Now we can create pools with two stables. How does this affect the bucket updates? [IBiPoolManager.BucketUpdateInfo](https://github.com/celo-org/celo-monorepo/blob/1098c8ab45b8e6328565d27abe26cbd4cee33217/packages/protocol/contracts/stability/interfaces/IBiPoolManager.sol#L32) only stores info for asset0, should we also be storing info for asset1 if it is a stable?

2022-09-13 14:06 UTC, bayological commented on packages/protocol/contracts/stability/BiPoolManager.sol
> +    // TODO: Stable bucket max fraction should not exceed available stable bucket fraction.
@sissnad Is this something we need to check here? Or is this even something to be concerned about or will the broker limits take care of this?

2022-09-13 14:06 UTC, bayological commented on packages/protocol/contracts/stability/BiPoolManager.sol
> +    // TODO: minSupplyForStableBucketCap gt 0 & is there an aggregated value that needs to be checked
@sissnad Is this something we need to check here? Or is this even something to be concerned about or will the broker limits take care of this?

2022-09-13 14:06 UTC, bayological commented on packages/protocol/contracts/stability/BiPoolManager.sol
> +  function getUpdatedBuckets(Pool memory pool)
How does this function work when bucket1 is a stable bucket?

2022-09-14 16:07 UTC, bowd commented on packages/protocol/contracts/stability/BiPoolManager.sol
> +    // TODO: minSupplyForStableBucketCap gt 0 & is there an aggregated value that needs to be checked
@bayological yeah I chatted with @sissnad about this today a bit, he's going to come up with a design that discusses both broker limits and bucket sizes.

2022-09-15 13:44 UTC, bayological commented on packages/protocol/contracts/stability/interfaces/IExchangeProvider.sol
> + * to communicate with different exchange manager implementations like the TwoAssetPoolManager
```suggestion
 * to communicate with different exchange manager implementations like the BiPoolManager
```

2022-09-16 14:26 UTC, merged