Squashed commit of the following:
celo-org/celo-monorepo pull request #9865
Opened 2022-09-15 16:35 UTC by martinvol

Brought already deployed RC7 commits to RC8 to prevent rollback on release, and confusing contract updates.

2022-09-15 16:54 UTC, aaronmgdr commented on packages/celotool/package.json
> -    "@celo/utils": "2.0.1-dev",
moving the @celo/** back to 1.5 is probably not right

2022-09-15 16:55 UTC, aaronmgdr commented on packages/faucet/package.json
> +{
facaucet was move to its own repo

2022-09-15 18:21 UTC, alecps approved these changes
Thanks!!

2022-09-15 18:38 UTC, aaronmgdr requested changes
requesting that old versions are not brought back. same with packages/ folders

2022-09-16 11:18 UTC, aaronmgdr commented on packages/sdk/wallets/wallet-walletconnect/lib/test/common.d.ts
> +/// <reference types="node" />
all the wallets/wallet-connect/** should be removed

2022-09-16 11:34 UTC, aaronmgdr approved these changes

2022-09-16 11:44 UTC, 0xarthurxyz commented
Thanks for the speedy review @aaronmgdr 🙏

2022-09-16 16:50 UTC, merged