Isabellewei/threshold tests
celo-org/celo-monorepo pull request #9873
Opened 2022-09-17 07:13 UTC by isabellewei

### Description

Added unit tests for the pnp and domain `thresholdState` function in the combiner

### Other changes

Fixed a bug in reading the signer length from the config.

### Related issues

- Fixes #9792

2022-09-17 07:18 UTC, isabellewei commented on packages/phone-number-privacy/combiner/test/unit/domainThresholdState.test.ts
> +      expectedCounter: 2,
This value is what the current code produces (threshold is 2, the 2nd value of the two enabled states is 2), but shouldn't we be returning 1 in this scenario?

2022-09-17 07:19 UTC, isabellewei commented on packages/phone-number-privacy/combiner/test/unit/domainThresholdState.test.ts
> +      expectedTimer: timer,
similar to above comment, the current code returns `timer`, but shouldn't this scenario return `timer-1`?

2022-09-21 00:03 UTC, alecps requested changes
Awesome work!!! I left a couple small comments about something I noticed with the pnpThresholdService (not from this PR), but overall this looks really good :)

2022-09-21 00:03 UTC, alecps commented on packages/phone-number-privacy/combiner/src/domain/services/thresholdState.ts
> +    const signersLength = JSON.parse(this.config.odisServices.signers).length
Nice catch!!

2022-09-21 00:03 UTC, alecps commented on packages/phone-number-privacy/combiner/test/unit/pnpThresholdState.test.ts
> +  // TODO: add tests with failed signer responses, depending on
Nit: can you make this TODO(2.0.0) ?

2022-09-21 00:03 UTC, alecps commented on packages/phone-number-privacy/combiner/test/unit/pnpThresholdState.test.ts
> +        logger: new Logger({ name: 'logger' }),
optional nit: You could also import and use rootLogger here

2022-09-21 00:03 UTC, alecps commented on packages/phone-number-privacy/combiner/test/unit/pnpThresholdState.test.ts
> +  const pnpThresholdStateService = new PnpThresholdStateService(config.phoneNumberPrivacy)
Could you somehow assert that threshold configured here is 2? You could either add a test for this or deep copy config and set the threshold explicitly

2022-09-21 00:03 UTC, alecps commented on packages/phone-number-privacy/combiner/test/unit/pnpThresholdState.test.ts
> +})
Looks great!! I think because we sort the responses by _remaining_ quota, we should probably have another block of tests where performedQueryCount and totalQuota both vary just to demonstrate that behavior

2022-09-21 00:03 UTC, alecps commented on packages/phone-number-privacy/combiner/test/unit/domainThresholdState.test.ts
> +  // TODO: add tests with failed signer responses, depending on
Nit: could you make this TODO(2.0.0)?

2022-09-21 00:03 UTC, alecps commented on packages/phone-number-privacy/combiner/test/unit/pnpThresholdState.test.ts
> +})
Also, I just noticed that the ordering of how we sort responses in pnpThresholdStateService may be backwards. Right now we're sorting responses into ascending order by remaining quota, and then taking the nth _most_ restrictive response as the threshold instead of the nth _least_restrictive. It doesn't get caught by the tests bc we have a 2/3 threshold, but it would get caught if we used a 3/4 threshold, for example. If this makes sense, could you reverse the order of the sorted responses in pnpThresholdStateService and update the tests to use a 3/4 threshold?

2022-09-21 00:03 UTC, alecps commented on packages/phone-number-privacy/combiner/test/unit/pnpThresholdState.test.ts
> +})
We should use the 3/4 threshold in domain tests too

2022-09-29 04:26 UTC, alecps approved these changes
Looks great!

2022-09-29 04:41 UTC, merged